//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int GameId { get; set; }
        public int CategoryId { get; set; }
        public string GameTitle { get; set; }
        public string Publisher { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int AgeClassification { get; set; }
        public System.DateTime Premiere { get; set; }
        public string ImageFileName { get; set; }
        public string GameDescryption { get; set; }
        public string Type { get; set; }
        public decimal GamePrice { get; set; }
        public bool Bestseller { get; set; }
        public bool Hidden { get; set; }
        public bool DigitalVersion { get; set; }
        public decimal Rating { get; set; }
        public int HardwareRequirementsId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
