//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareRequirement
    {
        public int HardwareRequirementsId { get; set; }
        public string System { get; set; }
        public string Processor { get; set; }
        public string Memory { get; set; }
        public string GraphicsCard { get; set; }
        public string DirectX { get; set; }
        public string HardDrive { get; set; }
    }
}
